image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: Bu2gG+2Ll5fL6/4fa920tDFnCS8uWXmIKBuefHhbJrsCI1qck/v0ERUkjMVonabO
before_build:
- nuget restore
build:
  project: GoLAAS.sln
  verbosity: minimal
after_test:
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[GameOfLife.Test]*" -target:"packages\NUnit.ConsoleRunner.3.8.0\tools\nunit3-console.exe" -targetargs:"/domain:single GameOfLife.Test/bin/debug/GameOfLife.Test.dll" -output:coverage.xml
  - packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover coverage.xml